Fix some style issues and add CI (#56)
zebscripts/AFK-Daily pull request #82
Opened 2021-08-14 17:28 UTC by ChillerDragon

2021-08-14 21:12 UTC, Zebiano requested changes
Hey! Thank you for this Pull Request. I like the CI addition, it's an interesting idea and will definitely come in handy! I'd just like to wait for PR #59 to be pushed to then implement it.

Also, I've made some comments that maybe you could address? Though honestly, I'd rather wait until #59 gets merged because the code there is quite different and maybe some or all of the changes you've made won't apply anymore. 

Thank you!

2021-08-14 21:12 UTC, Zebiano commented on deploy.sh
>          fi
Removing the `difference` variable and then attempting to use it on line `289` won't work. You'd have to change `289` to `"$now"`.

2021-08-14 21:12 UTC, Zebiano commented on .github/workflow/main.yml
> +      - name: Dependencys
```suggestion
      - name: Dependencies
```

2021-08-15 06:41 UTC, ChillerDragon commented on afk-daily.sh
> +#!/bin/bash
Woopsie

2021-08-15 06:45 UTC, ChillerDragon commented
Yea thought so I realized that #59 is there when I already submitted my pr. Yea so let's wait.

2021-08-29 17:34 UTC, kevingrillet commented on deploy.sh
> +            cd ./adb || exit 1
It's possible if the script doesn't have the right to use `mkdir`, that will raise a warning, then `cd` will do the same, and we will continue in the wrong folder :/

2021-09-16 20:39 UTC, kevingrillet requested changes

2021-09-16 20:39 UTC, kevingrillet commented on .github/workflow/main.yml
> +          echo 'disable=SC1091, SC2154' > .shellcheckrc
Mmh, I think we need to remove more things!

```
    "shellcheck.exclude": [
        "1090", // https://github.com/koalaman/shellcheck/wiki/SC1090
        "1091", // https://github.com/koalaman/shellcheck/wiki/SC1091
        "2034", // https://github.com/koalaman/shellcheck/wiki/SC2034
        "2154", // https://github.com/koalaman/shellcheck/wiki/SC2154
        "3057", // https://github.com/koalaman/shellcheck/wiki/SC3057
        "3060"  // https://github.com/koalaman/shellcheck/wiki/SC3060
    ],
```

2021-09-16 20:56 UTC, merged

2021-09-16 20:56 UTC, Zebiano commented
Thank you very much for this PR!